# Config file for air in TOML format

# Working directory
# . or absolute path, please note that the directories following must be relative to root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "~/go/bin/swag init -g backend/main.go -o backend/apps/swagger && go build -o ./bin/mcpgo ./backend"
# Binary file yields from `cmd`.
bin = "bin/mcpgo"
# Customize binary, can setup environment variables when run your app.
full_bin = "./bin/mcpgo"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these filename extensions.
exclude_ext = []
# Watch these directories.
include_dir = []
# Exclude these directories.
exclude_dir = ["assets", "tmp", "vendor", "backend/apps/swagger"]
# Exclude files.
exclude_file = []
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process, instead of directly kill process.
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
